---
- name: check for python
  stat:
    path: /usr/bin/python
  ignore_errors: yes
  register: systempython

- name: install python for debian based systems
  become: true
  raw: apt-get -y install python-simplejson
  ignore_errors: yes
  register: result
  when: systempython.stat is undefined or not systempython.stat.exists
  until: result is succeeded

- name: Now gather some facts
  become: true
  setup:
    gather_subset:
      - 'all'

- debug:
    msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
  when: ansible_default_ipv4.gateway is defined

- debug:
    msg: "System {{ inventory_hostname }} has gateway {{ ansible_default_ipv4.gateway }}"
  when: ansible_default_ipv4.gateway is defined
